<a href="https://colab.research.google.com/github/Leo-Foletto98/Deep_Learning/blob/main/E03_Leitura_de_Dados_Rev3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#@title
%%capture
!rm -rf *
!gdown 19b7ixRt9TU3Kb7r8NwiJ9UaK7Z34-9eH -O e03_ok.zip
!cd /content
!unzip e03_ok.zip
!pip install git+https://github.com/grading/gradememaybe.git

from IPython.display import YouTubeVideo
from gofer import ok

# 1 Upload do Arquivo

Use o espaço abaixo para fazer o upload do arquivo para o ambiente do Google Colab. Para isso você pode usar o comando `gdown` (lembre-se de colocar o sinal de exclamação `!` para chamar comandos na linha de comando, fora do Python).

In [ ]:
from google.colab import files
import io

upload = files.upload()
f = io.BytesIO(upload['Iris.csv'])

Saving Iris.csv to Iris.csv


In [ ]:
ok.check('e03_1.py')

# 2 Leitura do Arquivo

Escreva um laço que leia todas as linhas do arquivo, criando uma lista numa variável de nome 'd0', onde cada elemento da lista é uma string que corresponde a uma linha do arquivo.

In [ ]:
# Abrindo o arquivo para leitura
with open('/content/Iris.csv', 'r') as arquivo:
    # Método readlines() para ler todas as linhas e armazená-las em 'd0'
    d0 = arquivo.readlines()

# Agora, 'd0' contém todas as linhas do arquivo como elementos da lista
print(d0)
total = len(d0)
print(total)

['Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species\n', '1,5.1,3.5,1.4,0.2,Iris-setosa\n', '2,4.9,3.0,1.4,0.2,Iris-setosa\n', '3,4.7,3.2,1.3,0.2,Iris-setosa\n', '4,4.6,3.1,1.5,0.2,Iris-setosa\n', '5,5.0,3.6,1.4,0.2,Iris-setosa\n', '6,5.4,3.9,1.7,0.4,Iris-setosa\n', '7,4.6,3.4,1.4,0.3,Iris-setosa\n', '8,5.0,3.4,1.5,0.2,Iris-setosa\n', '9,4.4,2.9,1.4,0.2,Iris-setosa\n', '10,4.9,3.1,1.5,0.1,Iris-setosa\n', '11,5.4,3.7,1.5,0.2,Iris-setosa\n', '12,4.8,3.4,1.6,0.2,Iris-setosa\n', '13,4.8,3.0,1.4,0.1,Iris-setosa\n', '14,4.3,3.0,1.1,0.1,Iris-setosa\n', '15,5.8,4.0,1.2,0.2,Iris-setosa\n', '16,5.7,4.4,1.5,0.4,Iris-setosa\n', '17,5.4,3.9,1.3,0.4,Iris-setosa\n', '18,5.1,3.5,1.4,0.3,Iris-setosa\n', '19,5.7,3.8,1.7,0.3,Iris-setosa\n', '20,5.1,3.8,1.5,0.3,Iris-setosa\n', '21,5.4,3.4,1.7,0.2,Iris-setosa\n', '22,5.1,3.7,1.5,0.4,Iris-setosa\n', '23,4.6,3.6,1.0,0.2,Iris-setosa\n', '24,5.1,3.3,1.7,0.5,Iris-setosa\n', '25,4.8,3.4,1.9,0.2,Iris-setosa\n', '26,5.0,3.0,1.6,0.2,Iris-setosa\n', '2

In [ ]:
ok.check('e03_2.py')

# 3 Remoção de Cabeçalho e Contagem de Linhas

Utilizando a mesma variável `d0`, agora remova o cabeçalho (que deve ser o primeiro elemento da lista), e conte as linhas de dados. Grave o total de linhas numa variável de nome `total`.

In [ ]:
# Remoção do cabeçalho utilizando decode
if d0:
    d0.pop(0)  # Removendo o primeiro elemento (cabeçalho) da lista

# Total de linhas de dados
total = len(d0)
print(total)
# 'total' agora contém o número total de linhas de dados após a remoção do cabeçalho

print(d0)

150
['1,5.1,3.5,1.4,0.2,Iris-setosa\n', '2,4.9,3.0,1.4,0.2,Iris-setosa\n', '3,4.7,3.2,1.3,0.2,Iris-setosa\n', '4,4.6,3.1,1.5,0.2,Iris-setosa\n', '5,5.0,3.6,1.4,0.2,Iris-setosa\n', '6,5.4,3.9,1.7,0.4,Iris-setosa\n', '7,4.6,3.4,1.4,0.3,Iris-setosa\n', '8,5.0,3.4,1.5,0.2,Iris-setosa\n', '9,4.4,2.9,1.4,0.2,Iris-setosa\n', '10,4.9,3.1,1.5,0.1,Iris-setosa\n', '11,5.4,3.7,1.5,0.2,Iris-setosa\n', '12,4.8,3.4,1.6,0.2,Iris-setosa\n', '13,4.8,3.0,1.4,0.1,Iris-setosa\n', '14,4.3,3.0,1.1,0.1,Iris-setosa\n', '15,5.8,4.0,1.2,0.2,Iris-setosa\n', '16,5.7,4.4,1.5,0.4,Iris-setosa\n', '17,5.4,3.9,1.3,0.4,Iris-setosa\n', '18,5.1,3.5,1.4,0.3,Iris-setosa\n', '19,5.7,3.8,1.7,0.3,Iris-setosa\n', '20,5.1,3.8,1.5,0.3,Iris-setosa\n', '21,5.4,3.4,1.7,0.2,Iris-setosa\n', '22,5.1,3.7,1.5,0.4,Iris-setosa\n', '23,4.6,3.6,1.0,0.2,Iris-setosa\n', '24,5.1,3.3,1.7,0.5,Iris-setosa\n', '25,4.8,3.4,1.9,0.2,Iris-setosa\n', '26,5.0,3.0,1.6,0.2,Iris-setosa\n', '27,5.0,3.4,1.6,0.4,Iris-setosa\n', '28,5.2,3.5,1.5,0.2,Iris-setosa\

In [ ]:
ok.check('e03_3.py')

# 4 Remoção de Novas Linhas

Crie uma nova lista numa variável de nome `d1` onde cada elemento de `d1` corresponda à versão do mesmo elemento em `d0`, removendo o caractere de nova linha `\n` que aparece ao final de cada item. Assegure-se de que cada elemento da lista `d1` seja uma string simples (dependendo como você fez o upload, pode acontecer dos elementos estarem codificados, então decodifique caso necessário).

In [ ]:
# Nova lista d1 para armazenar os elementos sem o '\n'
d1 = []

# Iteração sobre os elementos em d0
for elemento in d0:
    # Método strip() para remover '\n' do início e do final de cada elemento
    data = elemento.strip()

    # Adicionando o elemento modificado à lista d1
    d1.append(data)

# Agora d1 contém os elementos de d0 sem o '\n'
print(d1)

['1,5.1,3.5,1.4,0.2,Iris-setosa', '2,4.9,3.0,1.4,0.2,Iris-setosa', '3,4.7,3.2,1.3,0.2,Iris-setosa', '4,4.6,3.1,1.5,0.2,Iris-setosa', '5,5.0,3.6,1.4,0.2,Iris-setosa', '6,5.4,3.9,1.7,0.4,Iris-setosa', '7,4.6,3.4,1.4,0.3,Iris-setosa', '8,5.0,3.4,1.5,0.2,Iris-setosa', '9,4.4,2.9,1.4,0.2,Iris-setosa', '10,4.9,3.1,1.5,0.1,Iris-setosa', '11,5.4,3.7,1.5,0.2,Iris-setosa', '12,4.8,3.4,1.6,0.2,Iris-setosa', '13,4.8,3.0,1.4,0.1,Iris-setosa', '14,4.3,3.0,1.1,0.1,Iris-setosa', '15,5.8,4.0,1.2,0.2,Iris-setosa', '16,5.7,4.4,1.5,0.4,Iris-setosa', '17,5.4,3.9,1.3,0.4,Iris-setosa', '18,5.1,3.5,1.4,0.3,Iris-setosa', '19,5.7,3.8,1.7,0.3,Iris-setosa', '20,5.1,3.8,1.5,0.3,Iris-setosa', '21,5.4,3.4,1.7,0.2,Iris-setosa', '22,5.1,3.7,1.5,0.4,Iris-setosa', '23,4.6,3.6,1.0,0.2,Iris-setosa', '24,5.1,3.3,1.7,0.5,Iris-setosa', '25,4.8,3.4,1.9,0.2,Iris-setosa', '26,5.0,3.0,1.6,0.2,Iris-setosa', '27,5.0,3.4,1.6,0.4,Iris-setosa', '28,5.2,3.5,1.5,0.2,Iris-setosa', '29,5.2,3.4,1.4,0.2,Iris-setosa', '30,4.7,3.2,1.6,0.2,Ir

In [ ]:
ok.check('e03_4.py')

# 5 Separação por Vírgulas

Crie uma nova lista em uma variável de nome `d2` onde cada elemento dessa lista seja uma sublista contendo as strings correspondentes a cada dado da string original, usando a vírgula como separador.

Por exemplo, transforme isso:

`'14,4.3,3.0,1.1,0.1,Iris-setosa'`

nisso:

`['14', '4.3', '3.0', '1.1', '0.1', 'Iris-setosa']`

Faça isso para todos elementos, na mesma ordem da lista original, gravando o resultado em `d2`.


In [ ]:
# Nova lista d2 para armazenar as sublistas
d2 = []

# Iteração sobre os elementos em d1
for elemento in d1:
    # Usando a função split(',') para separar os dados por vírgulas
    dados_separados = elemento.split(',')

    # Adicionando a lista de dados separados à lista d2
    d2.append(dados_separados)

# Agora d2 contém as sublistas de dados separados por vírgulas
print(d2)

[['1', '5.1', '3.5', '1.4', '0.2', 'Iris-setosa'], ['2', '4.9', '3.0', '1.4', '0.2', 'Iris-setosa'], ['3', '4.7', '3.2', '1.3', '0.2', 'Iris-setosa'], ['4', '4.6', '3.1', '1.5', '0.2', 'Iris-setosa'], ['5', '5.0', '3.6', '1.4', '0.2', 'Iris-setosa'], ['6', '5.4', '3.9', '1.7', '0.4', 'Iris-setosa'], ['7', '4.6', '3.4', '1.4', '0.3', 'Iris-setosa'], ['8', '5.0', '3.4', '1.5', '0.2', 'Iris-setosa'], ['9', '4.4', '2.9', '1.4', '0.2', 'Iris-setosa'], ['10', '4.9', '3.1', '1.5', '0.1', 'Iris-setosa'], ['11', '5.4', '3.7', '1.5', '0.2', 'Iris-setosa'], ['12', '4.8', '3.4', '1.6', '0.2', 'Iris-setosa'], ['13', '4.8', '3.0', '1.4', '0.1', 'Iris-setosa'], ['14', '4.3', '3.0', '1.1', '0.1', 'Iris-setosa'], ['15', '5.8', '4.0', '1.2', '0.2', 'Iris-setosa'], ['16', '5.7', '4.4', '1.5', '0.4', 'Iris-setosa'], ['17', '5.4', '3.9', '1.3', '0.4', 'Iris-setosa'], ['18', '5.1', '3.5', '1.4', '0.3', 'Iris-setosa'], ['19', '5.7', '3.8', '1.7', '0.3', 'Iris-setosa'], ['20', '5.1', '3.8', '1.5', '0.3', 'Iri

In [ ]:
ok.check('e03_5.py')

# 6 Entradas de Treinamento

Crie uma matriz no formato `array` do NumPy, numa variável de nome `d3`, contendo todos os dados da segunda, terceira, quarta e quinta colunas de `d2` transformados para o formato ponto flutuante (convertendo de string para número). Não inclua nem a primeira coluna (que é o id), nem a última coluna nessa conversão. Essa será a matriz de entradas.

In [ ]:
import numpy as np

# Inicializando uma lista vazia para armazenar os dados convertidos
dados_convertidos = []

# Iterando sobre as sublistas em d2
for sublista in d2:
    # Convertendo os elementos das colunas 2, 3, 4 e 5 para float
    colunas_numericas = [float(sublista[i]) for i in range(1, 5)]  # Colunas 2, 3, 4 e 5 correspondem às posições 1, 2, 3 e 4 na lista

    # Adicionando as colunas convertidas à lista de dados convertidos
    dados_convertidos.append(colunas_numericas)

# Convertendo a lista de dados convertidos em uma matriz NumPy
d3 = np.array(dados_convertidos)

# Agora d3 é a matriz de entradas no formato de ponto flutuante
print(d3)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [ ]:
ok.check('e03_6.py')

# 7 Saídas Desejadas

Crie um `array` do NumPy para as saídas desejadas, no formado _one-hot_. Para isso utilize as strings da última coluna de `d2`, verificando qual espécie de planta se refere cada string:

 `'Iris-setosa'` $\rightarrow$ `[1.0, 0.0, 0.0]`

 `'Iris-versicolor'` $\rightarrow$ `[0.0, 1.0, 0.0]`

 `'Iris-virginica'` $\rightarrow$ `[0.0, 0.0, 1.0]`

 Grave o resultado em um `array` do NumPy de nome `d4`, com o mesmo número de linhas de `d3`, onde cada linha de `d4` corresponde ao vetor _one-hot_ da saída desejada da respectiva linha de entradas de `d4`.

In [ ]:
# Criando um dicionário para mapear as espécies para vetores one-hot
mapeamento_especies = {
    'Iris-setosa': [1.0, 0.0, 0.0],
    'Iris-versicolor': [0.0, 1.0, 0.0],
    'Iris-virginica': [0.0, 0.0, 1.0]
}

# Inicializando uma lista vazia para armazenar as saídas desejadas
saidas_desejadas = []

# Iterando sobre as strings da última coluna de d2 e mapeie para vetores one-hot
for linha in d2:
    especie = linha[-1]  # A última coluna contém a espécie
    vetor_one_hot = mapeamento_especies[especie]
    saidas_desejadas.append(vetor_one_hot)

# Convertendo a lista de saídas desejadas em um array do NumPy
d4 = np.array(saidas_desejadas)

# Agora d4 contém as saídas desejadas no formato one-hot
print(d4)

[[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0.

In [ ]:
ok.check('e03_7.py')

# 8 Normalização das Entradas

Encontre o valor máximo e mínimo para cada uma das quatro colunas da matriz de entradas. Normalize os valores das entradas no intervalo entre zero e um, salvando o resultado em um `array` do NumPy de nome `d5`.

In [ ]:
# Encontrando os valores máximos e mínimos para cada coluna
minimos = np.min(d3, axis=0)
maximos = np.max(d3, axis=0)

# Normalizando os valores das entradas para o intervalo entre 0 e 1
d5 = (d3 - minimos) / (maximos - minimos)

# Agora d5 contém as entradas normalizadas
print(d5)

[[0.22222222 0.625      0.06779661 0.04166667]
 [0.16666667 0.41666667 0.06779661 0.04166667]
 [0.11111111 0.5        0.05084746 0.04166667]
 [0.08333333 0.45833333 0.08474576 0.04166667]
 [0.19444444 0.66666667 0.06779661 0.04166667]
 [0.30555556 0.79166667 0.11864407 0.125     ]
 [0.08333333 0.58333333 0.06779661 0.08333333]
 [0.19444444 0.58333333 0.08474576 0.04166667]
 [0.02777778 0.375      0.06779661 0.04166667]
 [0.16666667 0.45833333 0.08474576 0.        ]
 [0.30555556 0.70833333 0.08474576 0.04166667]
 [0.13888889 0.58333333 0.10169492 0.04166667]
 [0.13888889 0.41666667 0.06779661 0.        ]
 [0.         0.41666667 0.01694915 0.        ]
 [0.41666667 0.83333333 0.03389831 0.04166667]
 [0.38888889 1.         0.08474576 0.125     ]
 [0.30555556 0.79166667 0.05084746 0.125     ]
 [0.22222222 0.625      0.06779661 0.08333333]
 [0.38888889 0.75       0.11864407 0.08333333]
 [0.22222222 0.75       0.08474576 0.08333333]
 [0.30555556 0.58333333 0.11864407 0.04166667]
 [0.22222222 

In [ ]:
ok.check('e03_8.py')

# 9 Embaralhamento dos Dados

Misture as linhas dos dados dos valores de entradas de treinamento contidos em `d5` de forma aleatória. Faça o mesmo com as linhas das saídas desejadas em `d4`, de forma a manter a correspondência entre ambos. Chame a `array` resultante de dados de treinamento embaralhado de `x` e a `array` correspondente de saídas desejadas de `y`.

In [ ]:
# Combinando as entradas e saídas em um único conjunto de dados
dados_embaralhados = list(zip(d5, d4))

# Embaralhando os dados de forma aleatória
np.random.shuffle(dados_embaralhados)

# Separando novamente as entradas e saídas embaralhadas
x, y = zip(*dados_embaralhados)

# Convertendo x e y de volta para arrays do NumPy
x = np.array(x)
y = np.array(y)

# Agora, x contém os dados de treinamento embaralhados, e y as saídas desejadas correspondentes

In [ ]:
ok.check('e03_9.py')

# 10 Separação de Dados de Treinamento e Validação

Separe os pares de dados de treinamento e validação nas proporções 90%/10%, respectivamente. Chame a entrada e saída desejada dos pares de treinamento de `x_train` e `y_train`, e use os nomes `x_test` e `y_test` para os dados de validação. Os dados de validação devem corresponder às linhas finais dos pares de `array` originais `x` e `y`.

In [ ]:
# Determinando o tamanho do conjunto de validação (10% dos dados)
percentagem_validacao = 0.10
tamanho_validacao = int(len(x) * percentagem_validacao)

# Separando os dados em treinamento e validação
x_train = x[:-tamanho_validacao]
y_train = y[:-tamanho_validacao]
x_test = x[-tamanho_validacao:]
y_test = y[-tamanho_validacao:]

# Agora, x_train e y_train contêm os dados de treinamento, enquanto x_test e y_test contêm os dados de validação

In [ ]:
ok.check('e03_10.py')